create table if not exists public.handshake_action_logs (
  id bigint generated by default as identity primary key,
  handshake_id text not null,
  action_type text not null,
  signer_wallet text not null,
  milestone_id text,
  payload_version integer not null default 1,
  action_hash text not null,
  dedupe_key text not null,
  status text not null check (status in ('accepted', 'rejected')),
  verifier_source text not null check (verifier_source in ('edge-function')),
  persistence_mode text not null check (persistence_mode in ('remote', 'client')),
  error_code text,
  error_message text,
  request_payload jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists handshake_action_logs_dedupe_key_idx
  on public.handshake_action_logs (dedupe_key);

create index if not exists handshake_action_logs_handshake_id_idx
  on public.handshake_action_logs (handshake_id, created_at desc);

create index if not exists handshake_action_logs_action_type_idx
  on public.handshake_action_logs (action_type, created_at desc);
